version: "3.7"
services:
  database:
    build: ./mongo
    ports:
      - '27018:27017'
    user: root
    volumes:
      - ./data:/data/db
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongo.key:/etc/mongo.key
    networks:
      - finalpjnet
    restart: unless-stopped

  api:
    build: ./Server-api-temp
    ports:
      - '8887:8887'
    env_file:
      - ./Server-api-temp/.env
    environment:
      - MONGODB_URL=mongodb://root:1234@database:27017/finalpj?authSource=admin
    networks:
      - finalpjnet
    depends_on:
      - database
    restart: unless-stopped

  fontend:
    build: ./fontend
    ports:
      - 8080:80
    depends_on:
      - api
    networks:
      - finalpjnet
    restart: unless-stopped

  nginx:
    build: ./nginx
    image: nginx:alpine
    ports:
      - 8081:80
    depends_on:
      - fontend
    networks:
      - finalpjnet
    restart: unless-stopped
volumes:
  mongodb_data:
networks:
  finalpjnet:
    driver: bridge
